### ISSUE TITLE
Is it possible to support pdf rectangle annotation?

### ISSUE THREAD

**Issue by KuiyueRO** [RyotaUshio/obsidian-pdf-plus#1]
# First of all, thank you for making this useful plugin.

Some PDFs are scanned versions, is there any chance to support partial embedding or highlighting?

Just like 

```
[[xxx.pdf#page=2&area=x1,x2,y1,y2]]
```

**Comment by RyotaUshio** [comment]
Thanks for the idea. I do agree such a functionality should be very useful, and it will be technically possible. But I'm worrying about the risk of introducing too much plugin-dependent stuff. 

A workaround available now is the `offset=x,y,z` notation, where `x,y` specifies the upper-left corner position of the embedded area, and `z` specifies the zoom scale, if I understand correctly. e.g. `[[file.pdf#page=1&offset=x,y,z]]`

**Comment by KuiyueRO** [comment]
Thanks, I decided to just use `#page=3` .  :)

**Comment by RyotaUshio** [comment]
I think rectangle annotation is too important to discard. I do want to add this feature to this plugin.

But as I said, I don't want to go too far away from Obsidian's native syntax.

Given this constraint, another workaround available currently is 

1. First, open a target PDF file in an external PDF viewer application (such as Adobe Acrobat and PDF Expert).
2. Add a rectangle annotation in this external app.
3. Go back to Obsidian. Obsidian can link to an annotation with its ID, so you can link to the rectangle that you added in the last step. You can also make the link an embed by prepending `!` (but the annotation embed trimming feature has a problem now: #9).

Also, maybe this plugin could implement something like:

1. A user can use a rectangle area selection tool to add a rectangle annotation to a PDF file.
2. Once the rectangle annotation is embedded into the PDF file, the user can link to the rectangle using Obsidian's native syntax `[[file.pdf#page=<PAGE>&annotation=<ANNOTATION ID>]]`.

This could be doable.

**Comment by KuiyueRO** [comment]
If Obsidian's native syntax support `&width=xxx`.

Maybe you can be used `[[xxx.pdf#page=1&offset=x,y,z&height=xxx,&width=xxx]]`.

**Comment by RyotaUshio** [comment]
> If Obsidian's native syntax support &width=xxx.

Unfortunately it doesn't. But thanks for the suggestion!

**Comment by RyotaUshio** [comment]
Now that we can add annotations directly into PDFs, we have come a little bit closer to making this happen.

**Comment by RyotaUshio** [comment]
This feature has finally come true in [0.36.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.36.0)!
