### ISSUE TITLE
[FR] - Copy & auto-paste selection to right click menu

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#102]
### Describe your request

Hi,

It would be great if the right click menu after highlighting could be enhanced with copy & auto-paste options.

For example, right click a highlighted text then would have:

"Copy link to selection with format copy as quote"

and then

"Copy & auto-paste selection to annotation file with format copy as quote"

Advantage would be here, that also other own copy formats could be auto-pasted with this way from the right click menu.

For example: One of my copy format is "research". That format has tags inside.
I would then be able with right click and choose "Copy & auto-paste selection to annotation with format research".

This would be very helpful and I would be glad if you could implement it.

**Comment by RyotaUshio** [comment]
Hi, sorry for the late reply. Obviously, this is an important feature, but I wanted to improve how the auto-paste feature works in general so it took me some time.

From the next version, we will have an additional button for toggling auto-paste in the left ribbon (you can change the icon if you want to). As a result, auto-paste now works "symmetrically" as auto-focus, and your request can be achieved as below:

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/143e52a7-21a6-4210-9e83-c813d867a7e9

**Comment by N3C2L** [comment]
This is fantastic, thanks a lot!

Your solution with the new button is much cleaner than my proposal from above. 

Because with my proposal the right click menu would get cluttered  with the additionally copy & paste commands for every single custom copy format. This would have result in a long list for people with many custom copy formats. And it's better readable.

**Comment by RyotaUshio** [comment]
Released as [0.38.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.0)!
