### ISSUE TITLE
[FR] Disable fit width when a page link to a pdf is clicked

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#103]
### Describe your request

I am working in a specific zoom level in the pdf editor, and the zoom level should not be changed when clicking on links to pdf page in the annotation file.

If I set a custom zoom level in my pdf (for example with the pdf++ shortcuts for zoom), the checkmark for "fit width" disappears. That's what I want, because I am working in this zoom level with this PDF file.

But when I am clicking on a page link (from the annotation file for example) my zoom level is gone, because "fit width" is active again.

I saw only a zoom to fit toggle option in the settings for rectangle annotations, but not for regular annotations?

I would be glad I you could introduce an option to disable this fit with activation when clicking on links.

**Comment by RyotaUshio** [comment]
> I saw only a zoom to fit toggle option in the settings for rectangle annotations, but not for regular annotations?

Rectangular selection is what I built all from scratch by myself, but text selection/annotation links are made by the Obsidian core so things are a bit different.

I'll take a look at whether I can change the default bahaivor

**Comment by N3C2L** [comment]
Great, thanks.

**Comment by RyotaUshio** [comment]
These new options will be available from the next version.

<img width="1552" alt="Untitled" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/0365f3d1-b0b3-491f-9942-b349a651bf88">

**Comment by N3C2L** [comment]
Thank you for this addition!
