### ISSUE TITLE
[Feature] PDF files located outside the vault

### ISSUE THREAD

**Issue by RyotaUshio** [RyotaUshio/obsidian-pdf-plus#107]
### Discussed in https://github.com/RyotaUshio/obsidian-pdf-plus/discussions/60

<div type='discussions-op-text'>

<sup>Originally posted by **@antomonte** February 28, 2024</sup>
Hi,

your plugin is absolutely amazing!

Due to company privacy concerns, I try to avoid importing important PDFs into my vault.

Would it be possible to use the plugin with PDF files outside our vaults? (just located at our hard drives or company's cloud)

Best regards</div>

**Comment by RyotaUshio** [comment]
This is HUGE!

Work-in-progress docs page: https://ryotaushio.github.io/obsidian-pdf-plus/external-pdf-files

**Comment by RyotaUshio** [comment]
Beta-released as [0.38.0-beta](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.0-beta).
It seems to be working but there can be some bugs

**Comment by antomonte** [comment]
I'm not able to install it through BRAT.

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/5910/ed24ba2b-db8e-47e8-a21e-8cc12401791b)

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/5910/149a7035-5ef0-4cbb-aa30-77932e119d0a)

**Comment by N3C2L** [comment]
Try to insert this link:

https://github.com/RyotaUshio/obsidian-pdf-plus

**Comment by antomonte** [comment]
When I do like that, I'm receiving every time this warning (Windows)

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/5910/344914e9-d5ae-4983-b5d5-96110ba7e9ba)

... and doesn't allow to activate it 😞 

Any other idea?

**Comment by N3C2L** [comment]
This is a false positive (false alarm) by your antivirus.
Mr. Ushio would never integrate malware in his plugins.
You can add the pdf++ folder (...\.obsidian\plugins\pdf-plus) here as an exclusion in the windows defender settings:
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by antomonte** [comment]
I have no admin privileges to change such settings, so probably I'll not be able to use the plugin as long as the false positive is arisen 😭

**Comment by N3C2L** [comment]
If I upload the pdf++ files to virustotal.com no vendors has flagged this files malicious. 
So windows defender itself doesn't flag this files as malicious.
So there are no false positives.
So the problem must be on your side.
Maybe you haven't update your antivirus definitions or other system components of windows in a while?

**Comment by antomonte** [comment]
I'm not blaming these files in any manner. Most surely is what you say about the old database of that antivirus, but I cannot do anything with it, as it is a company laptop with many restrictions.

**Comment by RyotaUshio** [comment]
@antomonte Can you try manual installation?

1. Go to https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.0-beta3
2. From the "Assets" section, download 3 files `main.js`, `styles.css` and `manifest.json` and put them under `.obsidian\plugins\pdf-plus`.
3. Restart Obsidian

**Comment by RyotaUshio** [comment]
If it still fails, I'm totally okay with releasing it to the community plugin browser.

**Comment by RyotaUshio** [comment]
I've just released [0.38.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.0) to the official plugin browser so you'll be able to install it as usual.

Any feedback or comment about this new experimental feature is welcomed.

**Comment by N3C2L** [comment]
Thanks for this feature.

I was able to manually create a dummy pdf file with the a link to a local file in it. All the commands associated with your new feature are running fine in my vault.

But one thing does not work on my side (tested in a sanboxed vault on windows):

It's the command for the automatic dummy creation with this settings:

<img width="425" alt="obsi sandbox" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/74585843/ab02d588-c220-43c2-9f64-149868ab74c2">


The problem ist that no dummy files were created after clicking "create".
But as I said above, with the manually created dummy files the things are working great.

**Comment by N3C2L** [comment]
One idea for this dummy creation prompt is to add another button: "create+open". That would be great because we don't have to manually navigate to the folder after the creation.

**Comment by RyotaUshio** [comment]
@N3C2L Thanks for reporting! To me testing on Windows is a bit hard so I really appreciate this kind of reports.

I guess I was able to fix this, can you try 0.38.3?
https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.3

**Comment by RyotaUshio** [comment]
About "Create & open", I have tried that before but had some problems that I couldn't resolve. I will add it when I figure it out.

**Comment by N3C2L** [comment]
Thank you very much, it's working fine now!
Very useful for keeping the vault small sized (as you pointed out in your readme).
3,79 megabyte file size of the original PDF vs 65 byte file size with the dummy file. This is insane!

**Comment by antomonte** [comment]
Works like a charm!!!  Many thanks @RyotaUshio !!!

**Comment by RyotaUshio** [comment]
You can now use a bookmarklet to quickly create dummy files from your browser: https://ryotaushio.github.io/obsidian-pdf-plus/bookmarklet-to-create-dummy-pdf-files.html

@N3C2L  From [0.38.5](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.5), the created dummy file is automatically opened (with some limitations: see release note).

@antomonte Glad it worked out for you! Thanks for the idea 🙏 

I will close this issue, but feel free to create a new one if you have any suggestions. Thanks!

**Comment by N3C2L** [comment]
> @N3C2L From [0.38.5](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.5), the created dummy file is automatically opened (with some limitations: see release note).

Thanks for the auto-opening feature after creation.

I tested it (with new version 38.6) and it works great if the currently opened tab is a .md file.

However if the currently open tab is either a canvas file, an exalidraw file or a tab with the graph view open, then the dummy file will be created, but the opened file is blank in the pdf viewer.

Tested in a sandbox vault with no plugins on windows.

**Comment by RyotaUshio** [comment]
Thanks, file opening is temporarily disabled in [0.38.7](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.7). I will fix this as soon as possible.

**Comment by RyotaUshio** [comment]
Memo for the future myself: it turned out that it was due to `ObsidianViewer.open` was not called before `PDFViewerChild.loadFile`'s promise resolves

**Comment by RyotaUshio** [comment]
It should be fine in the latest version.

**Comment by RyotaUshio** [comment]
Thanks again for the feedback!

**Comment by candideu** [comment]
How do I get this to work with a PDF on my PC but not in my vault? What syntax should I be using?

**Comment by RyotaUshio** [comment]
It's documented here: https://ryotaushio.github.io/obsidian-pdf-plus/external-pdf-files.html#:~:text=and%20so%20on.-,Create%20dummy%20files%20from%20the%20command,-PDF%2B%2B%20offers%20an

But thanks for your sharing!
