### ISSUE TITLE
[FR] Preserve custom zoom level when opening PDF files again

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#113]
### Describe your request

If I am closing PDF files and reopen it later, my custom zoom level will be reset and "fit width" is active again. But I want to keep my custom zoom level of the PDF file even when I have closed my PDF file.

That would be really helpful.

**Comment by N3C2L** [comment]
I know you mentioned in another thread that the obsidian native pdf viewer is always restoring the fit width behavior.

But maybe another approach could help user like me or others which are working in specific zoom levels and don't use fit width at all:

Giving the user the possibility to set a default zoom level when opening a pdf file. 
The advantage would be here that after opening a pdf file will be no need for spamming the pdf++ zoom keys (because fit width is always making the pdf view way too large). 

Another pdf programs are displaying the zoom levels in percents but it's not something that I need urgent.

**Comment by N3C2L** [comment]
Awesome, thank you!

**Comment by RyotaUshio** [comment]
Released as [0.38.9](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.38.9). (file-by-file zoom level will be addressed together with #46)

**Comment by N3C2L** [comment]
That's truly fantastic, thank you very much. The custom zoom levels work very well and make opening the PDFs even more enjoyable. The zoom level input box is wonderful, superb! Also, the new dropdown menu at the top of the toolbar is really well done, and I'm pleased that simply hovering over it opens it. Great that you also want to implement the file-by-file zoom. Without PDF++ a good PKM journey in Obsidian wouldn't be possible; it's an essential tool for every mindful reader and researcher. Thank you very much.
