### ISSUE TITLE
[FR] Create a note with a template

### ISSUE THREAD

**Issue by bepolymathe** [RyotaUshio/obsidian-pdf-plus#118]
### Describe your request

Hi @RyotaUshio 

First of all, well done!  This plugin is great and will change a lot of things for me.  Really very useful and well thought out. 
 One thing I'm missing (or I haven't seen it) and would be very useful to me in my documentation work: being able to customize a template for the file when creating a note linked to a PDF (or any other recognized document) from this command

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/29939805/4848d27e-fbec-4b39-8ab3-316119a4084a)

Are you planning to include something like this?

**Comment by N3C2L** [comment]
Yes, you can use your own template:
1. Open the obsidian settings, 
2. On the left side scroll down to the PDF++ settings and click on it. 
3. On top click on this icon: <img width="24" alt="icoin" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/74585843/1b72bc18-fe23-4f1d-9571-efcaa7e68e1d">
and scroll to the 
"Template file path" heading.

**Comment by RyotaUshio** [comment]
Thanks N3C2L, I'm closing this as answered.
