### ISSUE TITLE
[FR] Don't reload a single PDF to memory multiple times

### ISSUE THREAD

**Issue by AOI-dev** [RyotaUshio/obsidian-pdf-plus#124]
### Steps to reproduce

1. Get yourself a scanned pdf file (100 pages, 100mb)
2. Create new note in a vault
3. Make x10 rectangular selections for each page (total count is 1000 links)
4. Watch your RAM go away

### Expected behavior

The links shouldn't take more space than an original file they are linked to. (In my case, I need 7gigs of RAM). 

### Actual behavior

The page shouldn't be duplicated in memory for each rectangular selection. 

This slows down my PC, also images don't load.

### Screen recordings or screenshots (sandbox vault)

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/32840029/107ef20d-a757-4edd-a31f-2fffa451666b)

### Obsidian debug info

-

### PDF++ debug info

```json
-
```

### Error messages

-

**Comment by AOI-dev** [comment]
Actually, I've gone through only 40 pages of my document and am already out of RAM

**Comment by RyotaUshio** [comment]
First of all, this is not an unexpected behavior, so I relabeled it as a feature request.

Second, it's unusual that a PDF document takes up 1MB for each page. It's too large. I recommend you compress it before importing it to your vault.

Third, I'm curious whether this inefficient memory usage is also the case for Obsidian's native embeds or not. Can you try it?

**Comment by RyotaUshio** [comment]
Also, you can enable the **Paste as Image** option in the PDF++ settings to avoid reloading the huge PDF document again and again.

**Comment by RyotaUshio** [comment]
Closing this as there is a workaround (paste as image). But it might be addressed in the future together with #46 and #113.
