### ISSUE TITLE
[FR] Mark page as read

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#133]
### Describe your request

In my old workflow, I marked a page as read with the pen tool. Back then, I drew a check mark on pages that I read. This was useful for pages where I didn't highlight anything on that page, but had feedback if I read that page already.

But I am thinking now of a another and faster method to mark a page as read.
I am thinking of a new button in the toolbar.

When pressed, an icon will be created to the actual page (written to the PDF directly, without creating anything to a separate annotation file).

The icon could display a check mark in the corner of a page.

The context menu of this icon could contain positioning options for that icon.  Something like "left corner", "right corner" (or other descriptions, where to place that icon on that page). 

This context menu would help people to position the icon afterwards, if they want to.

Such an addition would really help me and I would be glad if you could implement it.

**Comment by RyotaUshio** [comment]
I'm not sure how many people will benefit from this feature because the use case you described is very very specific or narrow (I'm not sure this is the right English word here).

A current workaround is using a link like `[[file.pdf#page=<PAGE NUMBER>&offset]]`. It will display a backlink icon at the upper-left corner of the specified page.

**Comment by RyotaUshio** [comment]
You might want to take a look at this section in the plugin settings to make it easier to integrate another PDF viewer app to accomplish your goal.

<img width="800" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/1c77e947-3c27-425c-b466-94481cdad481">

**Comment by N3C2L** [comment]
Hm. Maybe the use case could be increased with more icons (svg, lucide or emojis, I don't know which can be implemented) to write to the PDF directly.

People like me who don't remember every page or chapter that we have already read in this PDF would surely benefit from such a feature.

**Comment by RyotaUshio** [comment]
Thank you for your consideration, I will definitely rethink this when this issue gets upvoted by other users or a similar FR is submitted.

**Comment by N3C2L** [comment]
Thanks, appreciated!
