### ISSUE TITLE
[FR]Improved behavior of opening notes from pdf citation section

### ISSUE THREAD

**Issue by kazdonkai** [RyotaUshio/obsidian-pdf-plus#14]
設定によると，command+hover によって，PDFから引用部分のnoteが開かれる筈ですが，hover editor プラグインを使っていくと，hover 画面が出て，tab や new window では開かれません。
これは，キーがバッティングしているだと思いますが，そこで，この設定を，command+hover 以外にして欲しいです(ctr+hoverなど)。
また，ダブルクリックすると，新しいタブで必ず開かれますが，そうすると並べて見られないので，これも設定で変更できるようにして欲しいです。

よろしくご検討ください。
 

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/90127278/f6f1803d-33dd-477d-b7e6-4cbd9784f639

**Comment by RyotaUshio** [comment]
ありがとうございます。たしかに、Hover Editorについてはちゃんと考慮していませんでした。

> これは，キーがバッティングしているだと思いますが，そこで，この設定を，command+hover 以外にして欲しいです(ctr+hoverなど)。

これは（可能ではありますが）ちょっと大変ですね。実はcommandを指定しているのはこのプラグインではなく、Obsidianのpage previewコアプラグインの実装なので、これを別のキーに変えようと思うと、page previewのロジックを自前で実装し直すことになってしまいます。

短期的な解決策としては、Hover EditorとPDF++が有効になっている状態で、PDF++を一旦オフにしてからオンにし直し、すでに開いているPDFファイルを開き直すことで治るのではと思います。
（この問題の原因は、PDF++がロードされたあとにHover Editorがロードされた場合にHover EditorによってPDF++のロジックが上書きされることだと思われるので、Hover Editor -> PDF++の順で読み込まれるようにすればよいというわけです）

根本的な解決策がないか考えたいと思います。ありがとうございます。

> ダブルクリックすると，新しいタブで必ず開かれますが，そうすると並べて見られないので，これも設定で変更できるようにして欲しいです。

これは確かにそうですね。
https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian#Open+a+link
こちらにある修飾キーを押しながらダブルクリックした場合はその修飾キーを尊重して、なにも押さずにダブルクリックした場合は設定で指定した方法（"Open PDF links next to existing PDF tab"オプションのマークダウン版？）で開くというようにしようかなと思っています。

**Comment by RyotaUshio** [comment]
Hover Editorの件については、[0.21.2](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.21.2) で修正できたかと思います。PDF++が有効化されている状態で、後から追加でHover Editorを有効化した場合についてはどうしようもないのですが、その場合も"Reload the app without saving"コマンドでvaultを再起動すれば直るようにしたつもりです。

もしまだ不具合が残っていたら教えていただけると助かります。

ダブルクリックのほうは近いうちに実装したいと思います。

**Comment by RyotaUshio** [comment]
ダブルクリックのほうも、[0.21.3](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.21.3)で多少改善しました（正確には、cmd+hoverの場合と同じ挙動にしました）。

あとで設定項目も含めてもうちょっと見直したいので、このissueはopenしたままにしておきます。

もしなにか提案等あればまたぜひ教えてください。

**Comment by kazdonkai** [comment]
ダブルクリックでは、新しいwidowが開かれますが、重なってしまうので、移動する必要があって面倒です。
個人的には同じwindowでの分割をして欲しいので、設定で選択出来るようにして欲しいです。

**Comment by RyotaUshio** [comment]
> ダブルクリックでは、新しいwindowが開かれますが

ダブルクリック時のマークダウンファイルの開き方は、
"Action when hovering over highlighted text"オプションを"Open backlink"にしたときに表示される
"How to open markdown file with ..."オプションによって指定されるのですが、
昔の名残で"Action when ..."を"Popover preview of backlink"にすると"How to..."が表示されず、わかりにくいUIになっていました。
v0.24.0では"Action when..."にかかわらず当該オプションが表示されるようになる予定です。

> 同じwindowでの分割をして欲しい

なるほど、確かに毎回別のwindowが開かれるのは面倒ですね。
ただ、同一window内で画面分割すると、ファイルを開けば開くほど1ファイルあたりの表示面積が小さくなって、見づらくはないでしょうか？
「同一window内で新しいタブを開く」のほうが使いやすいのではと思ったりしましたが、どうでしょうか。

**Comment by RyotaUshio** [comment]
最後のリプライから１ヶ月ほど経ちましたのでこのissueは閉じます。必要であればまた新しくisuueを作成していただければと思います。
