### ISSUE TITLE
[FR] Usage of Control & Mousewheel step settings

### ISSUE THREAD

**Issue by lifehaschanged** [RyotaUshio/obsidian-pdf-plus#140]
### Describe your request

This plugin is a true lifesaver for PDF lovers. Thanks for its huge settings and features!
I adore to increase font size with Control & Mousewheel inside the PDF title, but a little problematic is only 50% or more steps are possible. 
Can you code a 10% steps with a single mousewheel scroll? (For example 10% smaller font size if Control & Mousewheel is scrolled up or down instead of the 50% or more like it is now).
That would be delightful for me.

**Comment by RyotaUshio** [comment]
Thanks for your kind words!

I quickly tested but in my environment, I can already change the zoom level by 10% if I scroll slowly enough.
Sorry that I can't help you but I recommend checking the configuration of your mouse.
