### ISSUE TITLE
[FR] A paste template whose name can be empty

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#146]
### Describe your request

I have added a display text format named Myself where the content is set to {{}}, but it doesn't work. What should I do?

![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/78469397/ca5af6ed-adb9-470e-98c4-90cfa1a92a57)

**Comment by RyotaUshio** [comment]
Each `{{ }}` must contain some meaningful expression (more specifically, PDF++ throws an error when it is evaluated as `undefined`)

To create an empty display text format that results in links like `[[file.pdf#page=1&selection=1,2,3,4]]`, use 
```
{{""}}
```
