### ISSUE TITLE
[Bug] Using PDF++ then Plug In Outliner doesn't work anymore (moving lines)

### ISSUE THREAD

**Issue by Schullinger** [RyotaUshio/obsidian-pdf-plus#147]
### Steps to reproduce

After highlights are implemented to note, outline Plug-In doesn't work anymore.

### Expected behavior

lines (as bullet-point list elements) should be able to be moved as expected through the plug-in "Outliner" in Obsidian

### Actual behavior

moving doesn't work

### Screen recordings or screenshots (sandbox vault)

-

### Obsidian debug info

see attached error message

### PDF++ debug info

```json
see attached error message
```

### Error messages

<img width="521" alt="CleanShot 2024-04-06 at 16 10 29@2x" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/159447121/706c0885-70b4-4e68-aeea-75516a1d3122">

**Comment by RyotaUshio** [comment]
Please follow the template.
