### ISSUE TITLE
[FR] Draw on top of PDF Files

### ISSUE THREAD

**Issue by rezatester94** [RyotaUshio/obsidian-pdf-plus#164]
### Describe your request
It would be great if the drawing feature on top of the PDF as well as a laser pointer cursor was added. Currently, to be able to draw on a PDF without having to import it into the "Excalidraw" plugin, I use the "[Open Gate](https://github.com/nguyenvanduocit/obsidian-open-gate)" plugin by "duocnv" to open a live view page from [Mozilla PDF.js](https://mozilla.github.io/pdf.js/web/viewer.html). Then opened my PDF files from there, so I could use the drawing feature. Because if you have to open PDF files that are quite large or have many pages, it would be completely irrelevant to use the "Excalidraw" plugin. But to open a PDF with the "Open Gate" plugin and then open Mozilla PDF.js is quite a difficult workflow. And I have to do it manually. Also, it is not possible to open more than one PDF file. So it would be very helpful if you could implement this drawing feature into the PDF++ plugin

![Draw on top of PDF](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/106055266/4b334f2c-1071-435c-ab28-407201c8b08a)

**Comment by RyotaUshio** [comment]
Hey @rezatester94,

As I mentioned in the [future request template](https://github.com/RyotaUshio/obsidian-pdf-plus/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml&title=%5BFR%5D+), PDF++ probably will not support handwriting/drawing for the time being. See the link therein for the details.

That said, we still have some workarounds. Do you use your desktop machine to add drawings? Then, I'd suggest using the "Open in default app" feature of Obsidian.

It's available from the command palette, the "more options" button (three dots), and the context menu in the file explorer:
  
<img width="800" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/128a587c-b88b-401e-b8d6-e0aa11f9a804">
 
<img width="800" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/10f26cee-d192-4a9b-8b6d-300dd5b2096b">

<img width="800" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/fe3c61c1-0bb1-4880-a510-88c08cf67d02">

In my use case, I use the Commander plugin to add the command to the tab bar.

Then you will be able to start drawing in your favorite PDF editing app.

For iPad workflows, you might find these links helpful:

- https://www.reddit.com/r/ObsidianMD/comments/1c0alf8/comment/kyvjf92/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
- https://github.com/RyotaUshio/obsidian-pdf-plus/discussions/42
