### ISSUE TITLE
[FR] Split right by default

### ISSUE THREAD

**Issue by dominiwe** [RyotaUshio/obsidian-pdf-plus#17]
Hi

Thank you for this plugin! It is something that [logseq](https://logseq.com/) has that I have been missing in obsidian.

But, would it be possible to add a feature so that wikilinks to PDFs (when pressed without any modifier keys) automatically open the PDF in a split view to the left or right? This would help with the muscle memory coming from logseq.

Also, for the option _How to open markdown file with ctrl+hover when there is no open markdown file_, would it be possible to add the option _Split left_?

Thank you!

Edit: To add more context, I am aware of [modifier keys](https://help.obsidian.md/User+interface/Tabs#Open+a+link). What I would like to do is overriding the default opening behavior _only_ for links to PDFs. So that I don't have to press the modifier keys when it comes to links to PDFs.

**Comment by RyotaUshio** [comment]
> would it be possible to add a feature so that wikilinks to PDFs (when pressed without any modifier keys) automatically open the PDF in a split view to the left or right?

Adding such an option to doable. I'll add this in a future release.
(Related: #3)

> Also, for the option How to open markdown file with ctrl+hover when there is no open markdown file, would it be possible to add the option Split left?

This is interesting. Although the Obsidian API does not provide a direct way to do this, it might be possible with some tricks.

**Comment by dominiwe** [comment]
Interesting! Thank you for the quick reply. In the meantime I will check out your code base and see if I can help/contribute myself.

**Comment by RyotaUshio** [comment]
Now it's available as the `How to open PDF links when there is no open PDF file` setting.

> In the meantime I will check out your code base and see if I can help/contribute myself.

Thanks a lot for the spirit!!! 🔥
