### ISSUE TITLE
[FR] Hotkeys for different annotation colors

### ISSUE THREAD

**Issue by gabbauer** [RyotaUshio/obsidian-pdf-plus#174]
### Describe your request

Hi, thx for the great work so far!
If it were possible to select the annotation colour of a text with a hotkey, that would be great. So if I could mark the text in the PDF with the mouse and then use a hotkey to select the colour in which I want to annotate the text instead of having to click on the color before or after that (e.g. control R for red markings and control B for blue markings). Especially with auto-paste = on, this would make marking extremely easy (even compared to other annotation tools such as Zotero).

**Comment by RyotaUshio** [comment]
Thanks! I will address this as a part of the linked issue #159.

For now, my recommendation is to set the option "Show the context menu right after selection text when ..." (obsidian://pdf-plus?setting=showContextMenuOnMouseUpIf) to "Always" and use the context menu to copy links.
It will enable a Zotero-like workflow.
For example:

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/529d0ad4-c0e5-47e4-a304-1e4312fc49ea

**Comment by RyotaUshio** [comment]
Closing this for now since it will be kept tracked at the linked issue.
