### ISSUE TITLE
[FR] Can I add a search button to make it easy to use on mobile?

### ISSUE THREAD

**Issue by violentrant** [RyotaUshio/obsidian-pdf-plus#179]
### Describe your request

Can I add a search button to make it easy to use on mobile?when you click the icon ,you can use the search function

**Comment by RyotaUshio** [comment]
@violentrant Hi, thank you for the nice suggestion. Although it will not be hard to implement this idea, I'm wondering if it can be enough to add an icon to the tab bar so that you can trigger the "Search in current file" command from it.

**Comment by RyotaUshio** [comment]
Closing this as not responded.

**Comment by violentrant** [comment]
> [@violentrant](https://github.com/violentrant) Hi, thank you for the nice suggestion. Although it will not be hard to implement this idea, I'm wondering if the [Commander](https://github.com/phibr0/obsidian-commander) plugin is enough. I mean, you can add an icon to the tab bar (or any other places) so that you can trigger the "Search in current file" command from it.
> 
> FYI this method also works not only for pdfs but also markdowns.
Thank you very much for your reply. I'm sorry I didn't see it before. Today, I submitted another one. I saw you reply to 179 items, and I found it specially. The scheme you mentioned is ok, but you will find many other contents at once, which will cause inconvenient interference. At present, the Pdf++ plug-in is on the Pc side, and the search box can be called through CTRL+F. However, it is still difficult on the mobile terminal, because it is impossible to input, so it is suggested whether a search box can be added on the mobile terminal to facilitate the user's use. If it is inconvenient, can you add a Command to search the current file in ctrl p? I can set an icon by using Command myself. Thank you very much for your reply and look forward to an early realization!
The main application scenario is to search and locate quickly when consulting materials.
