### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#18]
When a link is copied and pasted into a note, the link to the PDF (the clickable link with title+page for example) is only visible if "wiki-links" is enabled in the obsidian settings.

**Comment by RyotaUshio** [comment]
Thanks, this seems to be an upstream bug of Obsidian itself.
I've submitted a bug report: https://github.com/obsidianmd/obsidian-api/issues/154

**Comment by RyotaUshio** [comment]
I've just implemented a quick fix for this problem and released it as [0.25.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.25.0).

Feel free to re-open this issue if you find something is not working well.

**Comment by N3C2L** [comment]
Thank you for the quick fix.
