### ISSUE TITLE
[FR] need night-mod

### ISSUE THREAD

**Issue by jwqwuming** [RyotaUshio/obsidian-pdf-plus#186]
### Describe your request

reading PDF at night is hurt, wish to support auto night-mod

**Comment by RyotaUshio** [comment]
Use a dark mode and the "Adopt to theme" feature (which is Obsidian's built-in feature).

<img width="1552" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/1d627dfc-2a6b-45b7-9955-5588bd32fdd5">

**Comment by jwqwuming** [comment]
got it, thx very much
