### ISSUE TITLE
[FR] Automatic pasting into note after copying

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#19]
This feature would be amazing: If a text is highlighted with a marker, the text will be automatically inserted in the corresponding annotation note file. This corresponding annotation file is glued to the PDF file. So when opening the PDF, the note with the glued annotations will open as well in an adjacent pane.

**Comment by RyotaUshio** [comment]
How should the pasting position be determined? Sorted by the order in which the annotated texts appear in the PDF file?

**Comment by RyotaUshio** [comment]
It's possible to add this if it suffices to just append copied links one by one at the end of the associated markdown file.

**Comment by N3C2L** [comment]
Yes, thank you very much, that would be wonderful.

**Comment by RyotaUshio** [comment]
@N3C2L I'm wondering how a markdown file should be associated with a PDF file.
Currently, I have two options:

1. Specify a PDF via a property, like so
  ```markdown
  ---
  PDF: "[[file.pdf]]"
  ---
  ```
2. When you copy a link for the first time, you need to paste it manually to a markdown file. Then, PDF++ remembers the markdown file, and the next time on, it automatically pastes links to that markdown file.

The first option is adopted by many tools like the Annotator plugin, Zotero-related plugins, Logseq, ... and it will allow us to paste links even when the markdown is not opened.
However, a drawback is that it won't allow us to auto-paste links to other markdown files, i.e. we can use this feature for only one note per PDF file.

On the other hand, the second option will allow us to flexibly change which markdown to target.
It will be also useful when we want to put annotations about various PDF files in a single markdown file.
Its drawbacks include:
- we have to manually paste links at the first time
- we need to open the markdown file that links are pasted to

What's your thoughts?

**Comment by N3C2L** [comment]
I think the second option would be more versatile. 
Let's say my e-book has 20 chapters. I decide to read Chapter 12 and open the corresponding note file for Chapter 12 of that book. If later I want to read Chapter 8, I open the note file corresponding to Chapter 8 of the book. The advantage here is that you always have your automatically inserted notes in the right place, matching each chapter of the book.

This wouldn't be possible with option one. In this case, the text would always be automatically inserted at the end of the note file, regardless of which chapter you are currently on. This would result in the links from the automatically inserted notes being mixed up, sometimes Chapter 8, then Chapter 12, depending on where you read and marked.

There could also be an additional feature in the second option where the last used note file is always opened together with the PDF.

But perhaps in this second option, there might still be a way to skip the manual insertion of links at the beginning? For example, when the automatic insertion function is activated, a modal popup opens where you select the note file into which the notes will be automatically inserted.

**Comment by RyotaUshio** [comment]
Thanks for the feedback!

> But perhaps in this second option, there might still be a way to skip the manual insertion of links at the beginning? For example, when the automatic insertion function is activated, a modal popup opens where you select the note file into which the notes will be automatically inserted.

I see, but when you want to auto-paste, the corresponding markdown file is usually opened, right?
Then, a manual paste will not be that tedious IMO.

**Comment by RyotaUshio** [comment]
It's now released as the "Copy & auto-paste link to selection or annotation" command in 0.26.0.
See the "Copying links via hotkeys" section in the plugin setting for the details.

I'm closing this for now, but feel free to re-open it or create a new issue if you want propose improvements including the manual paste thing.

**Comment by N3C2L** [comment]
Thank you very much for the implementation!

There is a button in your plugin: "toggle select text to copy mode". May I ask you to implement another button with the function "toggle select text to copy & paste mode"? When this button is enabled, the highlighted text will be copied & pasted in the annotation file. I really would need this function, so that I don't have to push another button, only highlight the text with the mouse.

I would be very glad about this addition.

**Comment by N3C2L** [comment]
Hmm. Sorry, can't reopen this issue by myself. Because if the repository owner closes an issue, a normal user like me isn't allowed to reopen the issue.

**Comment by RyotaUshio** [comment]
It's also possible, but isn't it a bit annoying if a link is appended even when you make a mistake in selecting an appropriate range of text?

For example, suppose you want to select the word "Hello" but mistakenly select "Hell" only.
If either auto-paste or select-to-copy is disabled, you can avoid the failure link to "Hell" to be pasted into your note right away. However, if both of them are enabled, you will have to do manual deletion every time you make a mistake in text selection, which will be distracting.

So it seems to me that at least one of the auto-paste and select-to-copy is disabled. What do you think?

**Comment by N3C2L** [comment]
> It's also possible, but isn't it a bit annoying if a link is appended even when you make a mistake in selecting an appropriate range of text?

Could happen sometimes, yes, But with a double click on the highlighted text you will jump to the appended note and can delete the mistake there by deleting the linked text.

> So it seems to me that it's important that at least one of the auto-paste and select-to-copy is disabled. What do you think?

Yes, when one button is active, the other button should be deactivated. Otherwise, it would be confusing as to which function is currently active.

**Comment by RyotaUshio** [comment]
Closing this as merged into #33.
