### ISSUE TITLE
[FR] Disable left sidebar in embed

### ISSUE THREAD

**Issue by zuluwi** [RyotaUshio/obsidian-pdf-plus#2]
When the embed is rendered after opening the left sidebar in the pdf viewer, it also appears in the embed. If the embed is trimmed, the option to turn off the left bar is not accessible. Is it possible to add a feature to never show left sidebar in the embed?

![resim](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/111116092/1ccc6153-1f08-4575-bd5d-868385a81600)

**Comment by RyotaUshio** [comment]
Released as [0.11.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.11.0)!
