### ISSUE TITLE
Mixed Colors when clicking links

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#23]
When a page link is clicked in the annotation file tab, the text in the PDF tab is focused but highlighted again with the yellow color (the yellow color is only temporary). However, the problem now is that if you have highlighted your text in the PDF with the green color and then click on a page link in the annotation file, the green color mixes with the yellow color, making it difficult to read and not looking good. Therefore, an additional option would be good: that PDF++ does not display any additional highlight when clicking on a page link.

**Comment by RyotaUshio** [comment]
Does it help to turn on "Clear highlights after a certain amount of time" option and then set "Highlight duration (sec)" to some small value?

**Comment by RyotaUshio** [comment]
Probably I can implement an option that eliminates the yellow highlights in the first place, but I think some highlights should be displayed to indicate which part of the text is the link target. 
So shortening the highlight duration maybe achieves a good balance.

**Comment by N3C2L** [comment]
> Does it help to turn on "Clear highlights after a certain amount of time" option and then set "Highlight duration (sec)" to some small value?

YES. Thank you. I did miss that option. I think this option should be enabled by default when installing PDF++.

**Comment by N3C2L** [comment]
> Probably I can implement an option that eliminates the yellow highlights in the first place, but I think some highlights should be displayed to indicate which part of the text is the link target. So maybe shortening the highlight duration achieves a good balance.

It's fine now. See my reply above.
