### ISSUE TITLE
[FR] Sorting Annotations by Page Number

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#24]
I don't know if it's possible, but this function would be awesome: When executed, the annotations in the markdown file will be sorted by page number. This would be helpful if the annotations are mixed up from different chapters on different pages, and you are using only one annotation markdown file.

**Comment by RyotaUshio** [comment]
I'm afraid it's impossible without some additional rules.
Links such as `[[file.pdf#page=1]]` can be sorted, but it's hard to determine how many lines around each link should be considered as associated memos. For example, consider "Here you write some comments about the quote" below.

```
> ([[file.pdf#page=1|file, p.1]]) Hello, world

Here you write some comments about the quote. But it's difficult to automatically determine this line is associated with it.
```

**Comment by RyotaUshio** [comment]
You can define your own rule, for example enclosing each annotation/memo with three hyphens, and then write some script to sort annotations by page number.
