### ISSUE TITLE
[Bug] PDF++ does not recognize the latest installed version of Obsidian.

### ISSUE THREAD

**Issue by Txindoki666** [RyotaUshio/obsidian-pdf-plus#242]
### Steps to reproduce

1 Open Obsidian.
2 I get a message from pdf++ that the Obsidian version is old. Show link to Obsidian web site to download the latest version.

### Expected behavior

Recognize Obsidian version.

### Actual behavior

The box stays open and I have to close it to use obsidian.

### Screen recordings or screenshots (sandbox vault)

![Captura de pantalla 2024-07-11 164255](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/131624488/b179057a-1392-4099-a0e4-93f3267a1ebf)

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 38
		1: Annotator v0.2.11
		2: Auto Link Title v1.5.4
		3: Calibre v1.0.8
		4: Highlightr v1.2.2
		5: Kobo Highlights Importer v2.0.0
		6: LanguageTool Integration v0.3.7
		7: Omnisearch v1.23.1
		8: Recent Files v1.4.1
		9: Simple Embeds v1.15.0
		10: Templater v2.3.3
		11: Text Extractor v0.5.2
		12: Timelines v0.3.2
		13: Zotero Integration v3.1.8
		14: Book Search v0.7.4
		15: File Tree Alternative v2.6.0
		16: Translate v1.4.9
		17: Copilot v2.5.2
		18: Editing Toolbar v2.4.16
		19: Tag Wrangler v0.6.1
		20: Note Linker v1.2.4
		21: Extract Highlights v0.0.18
		22: Settings Search v1.3.10
		23: Kanban v2.0.51
		24: Custom Frames v2.4.7
		25: Hover Editor v0.11.20
		26: Media DB v0.7.2
		27: YTranscript v0.9.2
		28: Enhancing Export v1.10.6
		29: Advanced Canvas v3.0.6
		30: Canvas Mindmap v0.1.11
		31: Smart Connections v2.1.86
		32: Markmind v2.0.1
		33: Importer v1.6.4
		34: Footnote Shortcut v0.1.3
		35: Remember cursor position v1.0.9
		36: Style Settings v1.0.8
		37: Smart Connections Visualizer v1.0.12
		38: PDF++ v0.40.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### PDF++ debug info

```json
Hi, when I open Pdf++ it indicates that I am not using the latest version of Obsidian. This is an error, since Obsidian is updated. I have reinstalled Pdf++, but the problem continues.
```

**Comment by RyotaUshio** [comment]
According to your debug info, your installer version (v1.5.3) is indeed outdated. 

> Obsidian version: v1.6.5
> Installer version: v1.5.3

Note that "Installer version" and "Obsidian version" are different. You can click the "what is installer version?" button in the message for more information.

<img width="207" alt="image" src="https://github.com/user-attachments/assets/6b7eeffb-10bb-4dbe-9487-771f5e4698c4">

**Comment by Txindoki666** [comment]
Thank you very much, I didn't understand the difference between software version and installer version. But it is now solved and PDF++ works perfectly.
Thanks again.
