### ISSUE TITLE
[FR] Get Google Scholar Citation like a plugin in Chrome/Edge Browser

### ISSUE THREAD

**Issue by qianlong0502** [RyotaUshio/obsidian-pdf-plus#246]
### Describe your request

I notice that you have implemented a feature to allow users to check the citation of some papers quickly. However, I found there is a plugin in Chrome/Edge browser, of which the link is https://chromewebstore.google.com/detail/dahenjhkoodjbpjheillcadbppiidmhp, named Google 学术搜索 PDF阅读器, and it is more convenient than your implementation for now. I suggest that you could refer to this plugin to enhance your implementation.

I appreciate your plugin and it becomes one of the most frequent plugin I used in Obsidian. Thanks for your efforts.

**Comment by RyotaUshio** [comment]
Thanks for the suggestion. In fact, this extension by Google is exactly what inspired me to implement the citation hover feature of PDF++.
I would like to know more about the original implementation, but it's not open-source, so unfortunately it's not easy (although I can see the minified code).
Also, I believe the original extension is backed up by Google's powerful AI models, which is not easy to integrate into this plugin.

But if you (or anyone seeing this!) has ideas for improving the hover feature, I'd appreciate your contribution! Ask me any questions if you're interested in the implementation of this plugin.
