### ISSUE TITLE
[Bug] Arrows in File Search

### ISSUE THREAD

**Issue by LeonStra** [RyotaUshio/obsidian-pdf-plus#247]
### Steps to reproduce

Go to any file and press Strg + F. 

### Expected behavior

The right arrow pointing down.

### Actual behavior

You get two arrows pointing up

![image](https://github.com/user-attachments/assets/d96e1b66-84f2-43e4-b0de-7c20a1767d1d)

### Screen recordings or screenshots (sandbox vault)

![image](https://github.com/user-attachments/assets/d96e1b66-84f2-43e4-b0de-7c20a1767d1d)

### Obsidian debug info

-

### PDF++ debug info

```json
-
```

### Error messages

-

**Comment by RyotaUshio** [comment]
See #244
