### ISSUE TITLE
[FR] Icons for custom copy formats

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#25]
Selecting a text with the marker > right click > add bookmark. When "add bookmark" is clicked from this context menu, it creates a special page link in the annotation file. Maybe this link is then named "Bookmark:" And after this word "Bookmark:" the user can name this bookmark, for example "Bookmark: Chapter 3".

**Comment by RyotaUshio** [comment]
Can you elaborate on your idea more? Do you want to have an easy way to copy & auto-paste a link that looks like `[[file.pdf#page=...&selection=...|Bookmark: ]]`?

**Comment by N3C2L** [comment]
Thank you, this custom copy format option is very useful.
Maybe you want to add "bookmark" as a custom format option in the settings for new users as a default setting when they install PDF++? So new users can use this option for bookmarks. But maybe another bookmark icon could be introduced left of the selected text. Like this icon instead of the text marker color:
https://www.flaticon.com/free-icon/bookmark_786352
Maybe in the custom copy format setting new icons could be added for bookmark links or special links in the future for other custom copy formats?

**Comment by RyotaUshio** [comment]
> add "bookmark" as a custom format option in the settings for new users as a default setting when they install PDF++

It seems to me that a custom format with a specific display text like "bookmark" is not a very common use case shared by most users. I'd like to keep the default minimalistic so I'm afraid I will not add this as default.
However, providing a list of useful formats on the wiki page of this repository would be helpful. 

> in the custom copy format setting new icons could be added for bookmark links or special links in the future for other custom copy formats

**Comment by RyotaUshio** [comment]
Closing this as merged into #33.
