### ISSUE TITLE
[FR] Allow copying text in citation hover

### ISSUE THREAD

**Issue by fedemengo** [RyotaUshio/obsidian-pdf-plus#252]
### Describe your request

When hovering on a citation, I'd like to be able to copy the citation title directly, rather that having to click on it, be brought to the ref in the citation section, copy the text and navigating back to were I left off. 

This would make looking up citation much smoother

**Comment by RyotaUshio** [comment]
Thanks, this will be added in [0.40.9](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.9).
