### ISSUE TITLE
[FR] Case Sensitive Search Bar

### ISSUE THREAD

**Issue by DejaVoodoo-1** [RyotaUshio/obsidian-pdf-plus#255]
### Describe your request

I LOVE the PDF++ plugin.  It is one of the single most useful plugins I've ever downloaded.  The only thing that bothers me is that the search appears to always be case sensitive, so I will oftentimes search from an outside viewer and make my links in obsidian.

**Comment by RyotaUshio** [comment]
Thanks!

Case-sensitive search is already possible even without this plugin p- just click the "Aa" icon in the search bar.
