### ISSUE TITLE
Add custom color palette actions to right click menu

### ISSUE THREAD

**Issue by programlich** [RyotaUshio/obsidian-pdf-plus#26]
Awsome plugin, great work!

Would it be possible to show the custom color palette actions also in the right click menu, that pops up, when I right click the selected text? Now, only the defualt options pop up so I have to go back and select my custom action in the top menu if I need one of theese.

**Comment by RyotaUshio** [comment]
Thanks for the kind words!

Yeah, it's something that I've had in my mind for a while and I want to add before long.
