### ISSUE TITLE
[Bug] Exporting Comments in PDF only pulls from loaded view window

### ISSUE THREAD

**Issue by samanthavenialogan** [RyotaUshio/obsidian-pdf-plus#260]
### Steps to reproduce

1. Open a PDF document of more than 30-40 pages. 
2. Used example report of 37 pages here: [Report-Content or Context Moderation_Artisanal Community-Reliant and Industrial Approaches-Robyn Caplan-moderation-2018.pdf](https://github.com/user-attachments/files/16742783/Report-Content.or.Context.Moderation_Artisanal.Community-Reliant.and.Industrial.Approaches-Robyn.Caplan-moderation-2018.pdf). 
3. Proceed to highlight the document and provide annotated comments for a variety of highlights throughout the full document.  
4. Scroll to the middle point of the document at a zoom of 150% for the document. 
5. Use the global copy/paste for highlights and comments provided in PDF++. copy all highlights with comments provided as displayed in the following discussion threads: https://github.com/RyotaUshio/obsidian-pdf-plus/discussions/132#discussioncomment-9931568
6. after pasting comments into a new note, or into NotePad++ you will see that comments are only present on the page you are on +/- ~5 pages corresponding with the viewer's load of the PDF's pages. 
7. Zoom out gradually to 125%, 100%, 50%, 20%, and 10% as your repeat steps 3 and 4 for each zoom. 
8. You will see that the comments captured by the copy/paste increase in a linear fashion with the view window because the loaded view window is forced to render more and more comments due to the zoom. More pages loaded in the viewer = more comments loaded. 
9. There is a ceiling to how this zooming workaround functions for documents that cannot properly display all of the pages - it will not be able to take all comments for documents over 30 pages at 10% because you cannot feasibly fit that many pages on the document viewer window. 
10. You can further extend this by putting the document into 2 page view but even this is only a limited workaround for larger documents such as books. 

### Expected behavior

The expected behavior is that the document will copy/paste all comments attached to all highlights and annotations regardless of the viewer for the PDF. This works for highlights but it does not work for the annotations attached to those highlights. 

### Actual behavior

At the moment the document will take all highlights from the document regardless of whether they are loaded, but attached annotated comments will not copy/paste in full - it will only do so for the targeted document view +/- 5 pages which are loaded in and waiting to be displayed on the window view. The comments seem hindered by the PDF's function of a 'lazy-load-like' feature. 

### Screen recordings or screenshots (sandbox vault)

In the below footage the following document: [Report-Content or Context Moderation_Artisanal Community-Reliant and Industrial Approaches-Robyn Caplan-moderation-2018.pdf](https://github.com/user-attachments/files/16742741/Report-Content.or.Context.Moderation_Artisanal.Community-Reliant.and.Industrial.Approaches-Robyn.Caplan-moderation-2018.pdf) was marked up with comments from the start through to the end of the document. The document was copied at 200%  from the middle of the document (pg. 20) using the standard copying procedure for global copies. The result was subsequently placed into NotePad++.  The Notepad was then checked for whether the comments at the start and the end of the document were properly copied. The comments copied to page 26 on the bottom but failed to capture the comments on the 1st-7th pages. 

https://github.com/user-attachments/assets/bb8a04d0-440a-43f8-ba50-b1efb50abde5

First comment on page 2: 
![image](https://github.com/user-attachments/assets/d1436dc8-d8b5-44c2-8ac8-da2342d9f017)

Last comment on page 34: 
![image](https://github.com/user-attachments/assets/b4e8df05-d432-4df5-b2d7-d3a2f5cba036)

Notepad++ copy/paste results first comment recorded relates to a highlight on page 17 and last on page 34

![image](https://github.com/user-attachments/assets/fbaeabd6-9836-4ce0-858b-79a2a2338d44)

![image](https://github.com/user-attachments/assets/85968ad5-3337-4322-bdf9-01b8204dfb69)

### Obsidian debug info

irrelevant - issue is not technically an obsidian bug.

### PDF++ debug info

```json
irrelevant - issue would not show for PDF++ bugs because this is not technically a bug. This seems to be a limitation of the current implementation.
```

### Error messages

N/A

**Comment by jkjoker** [comment]
我也发现了类似的问题，提取内容时，目前只能提取高亮，而不能提取注释。

**Comment by samanthavenialogan** [comment]
Hey just wanting to follow up on this issue @RyotaUshio? Is this something you'd like to cover or should we leave it be as is? It's affecting my daily work but I love the plugin too much otherwise to switch due to those issue?

**Comment by samanthavenialogan** [comment]
Hey thanks @RyotaUshio! It looks like the issue is resolved so far as I can tell ^^ I REALLY appreciate you having done this! 

I've confirmed that the issue is no longer an issue on 3 new documents in addition to the above. For one such example I tested a totally new book with 240 pages on the prior release version that I had reported the bug on (I didn't pull that version number, sorry). The issue was still present on the following book document BEFORE updating. 

[book-The Platform Society_ Public Values in a Connective World-moderation-José van Dijck-2018.pdf](https://github.com/user-attachments/files/17164334/book-The.Platform.Society_.Public.Values.in.a.Connective.World-moderation-Jose.van.Dijck-2018.pdf)

to test that the book was impacted by the bug prior to updating I placed a comment on page 3 with the keyword "BRUG" on it. Then I placed an additional comment on page 55 with keyword "PULL". I went to page 20 and C/Ped it the full highlights as intended. Upon CP/ing it to Notepad++ the bug showed. As expected it did not pull the comment on page 55. After repeating these steps with my window on page 40 it pulled page 55 but not page three. This bug's before is present. 

AFTER updating to the current release from 2 days ago (0.40.11), I copied the same comments with page 3 loaded, page 55 loaded, page 26 loaded and to cover all of my bases page 200 loaded. In all cases comments were showing regardless of the page load. 

I'll update here if anything further happens and I hope this helps any others experiencing the bug as well!

**Comment by jkjoker** [comment]
Hi!  @RyotaUshio  Thank you so much for fixing the issue!

I tested it with version 0.40.11 on 3 PDF files, including one with 10 highlights (2 of which have comments), and all of them were extracted correctly. The number and display are all good.
