### ISSUE TITLE
[FR] Can I fixed the copy format with different color？

### ISSUE THREAD

**Issue by BruceAE86** [RyotaUshio/obsidian-pdf-plus#268]
### Describe your request

For example:
When I open auto-copy and select color red, the paste format is Quote--text.
When I select color blue, the paste format is callout---emoji.

Give me a option that in this pdf & md, I can fix this selection with color.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/ac6abcf4-e702-471d-be71-04ee2908123b">
Then I can write the note efficiently.
thanks.

**Comment by RyotaUshio** [comment]
This feature will be addressed as a part of #159.
