### ISSUE TITLE
[Bug] PDF files that have an "accent" are not opened by the plugin. e.g. "tássio_article.pdf"

### ISSUE THREAD

**Issue by tassiovirginio** [RyotaUshio/obsidian-pdf-plus#274]
### Steps to reproduce

PDF files that have an "accent" are not opened by the plugin. e.g. "tássio_article.pdf"

### Expected behavior

I expected it to open any type of PDF, regardless of the file name.

### Actual behavior

It shows a blank screen.

### Screen recordings or screenshots (sandbox vault)

no

### Obsidian debug info

...

### PDF++ debug info

```json
...
```

### Error messages

...

**Comment by RyotaUshio** [comment]
You reported something that has nothing to do with PDF++ without reading or following the template.
https://forum.obsidian.md/t/linux-images-and-pdfs-dont-load-if-vault-contains-accented-letters-such-as-e-non-english-non-ascii-cjk-umlauts/42010

**Comment by tassiovirginio** [comment]
Thanks, I installed the .deb version and it fixed the problem.
