### ISSUE TITLE
[FR] rectangular selection nonEmbed setting

### ISSUE THREAD

**Issue by AkumaShisen** [RyotaUshio/obsidian-pdf-plus#275]
### Describe your request

Trying to use pdf++ i noticed that for my usecase i didnt necessarily need to embed the link. Looking through the settings and later the codebase i saw there wasn't a setting which justgave the option of leaving the "!" out of the text put into the clipboard. 
In the future having a similar style of customizability as the highligher option has in the settings would be great.

**Comment by RyotaUshio** [comment]
Thanks for the nice suggestion. I think this can be seen as a special case of #106, so I will close this issue. I will address this as a part of #106 in the near future.
