### ISSUE TITLE
[FR] Highlighting text without needing to paste it into annotation files

### ISSUE THREAD

**Issue by JzyGavin7** [RyotaUshio/obsidian-pdf-plus#278]
### Describe your request

Thank you for providing such amazing tools! I hope we can have a feature that allows us to highlight text directly without needing to paste it into annotation files. Sometimes, I just want to highlight text without adding comments. I'm not sure if this feature is already available, as I haven't found a way to do it

**Comment by RyotaUshio** [comment]
Thanks, I'd suggest using the Pdf Annotator plugin mentioned here in the readme: https://github.com/RyotaUshio/obsidian-pdf-plus?tab=readme-ov-file#note-on-saving-annotations-directly-in-pdf
