### ISSUE TITLE
Bug with copy & auto-paste link command

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#28]
If I highlight a text passage (copy as quote format) with the marker and then execute the "copy & auto-paste link" command with the hotkey, copy formats like "copy as quote" often result in wrong focusing in the annotation tab. The text input cursor (the blinking cursor while typing) jumps around inside the copied text selection or above.
You can reproduce it by creating several links with the copy as quote format, but every time use the copy & auto-paste command. While creating the links look at the open annotation file in the other tab: It doesn't synchronize with the pasted links. The focus in the annotation tab keeps on the first pasted link, and doesn't move to the bottom of the tab where new links are pasted.

**Comment by N3C2L** [comment]
There is another bug with this copy & auto-paste command:
How to reproduce:
1. Open a fresh PDF tab and a fresh annotation file in another tab.
2. Select a text range and create a link with the "copy as quote" format.
3. Paste it manually in the annotation file.
4. Because we added the link manually, the copy & auto-paste command should work.
5. But it doesn't work with the "copy as quote" format: "Cannot auto-paste because it's the first time. Please manually paste the link."
6. The first link detection for this command works only if a link is inserted with the other 2 format presets: copy embed of selection + copy link to selection.
7. When the link is manually inserted with one of them, only then the "copy as quote" format is working with the copy & auto-paste command.

**Comment by RyotaUshio** [comment]
Wow, sorry now I realize that I made a silly mistake and it was causing problem 1!! Will release a fix soon.

**Comment by RyotaUshio** [comment]
Released: 0.27.9

**Comment by N3C2L** [comment]
Thanks, it's better now!

I found something interesting where the manual paste detection does not work depending on copying formats:
When you select the text and right click > copy link to selection 
When you select the text and right click > copy as quote
In both cases the manual paste detection does not work.
It's only working when you click the colors palette above to link it.

**Comment by RyotaUshio** [comment]
@N3C2L Okay now I see what's happening!

The right-click menu is in fact out of control of PDF++. It is left default.

(You can see this by modifying the "copy as quote" format in the setting. When you copy a link from hotkeys or color palettes, the new custom format is applied, but it is not applied if you copy one from right-click menu)

This is why the manual-paste detection doesn't work after copying links via right-click.

There is a feature request (#26) for replacing the Obsidian-native right-click menu with a custom one.
Resolving is will also fix this issue.

**Comment by RyotaUshio** [comment]
So for the time being, I recommend you use the copy command without auto-paste via a hotkey or a color palette for the first time, and then use the auto-paste command from the second time on.

**Comment by RyotaUshio** [comment]
@N3C2L Now [0.27.10](https://github.com/RyotaUshio/obisidan-pdf-plus/releases/tag/0.27.10) has a custom context menu, which will resolve this issue.

**Comment by RyotaUshio** [comment]
Hmm... that's strange, and in my environment, it's working just fine...

- Can you try reloading the app after updating PDF++?
- If it doesn't help, can you show me a screen recording of where this bug is happening, and also show me the result of the command "Show debug info"?

**Comment by RyotaUshio** [comment]
I've created a new issue #34 for this problem. Let's continue there.
