### ISSUE TITLE
[FR] Create dummy file by drag and dropping external files

### ISSUE THREAD

**Issue by ThinkWithPbody** [RyotaUshio/obsidian-pdf-plus#285]
### Describe your request

I store all PDFs outside of my vault. So far dummy files have been working great for that use case, but because of how often I had to use the Create dummy file for external PDF command, I wished there was a faster alternative that let me use file explorer and drag and drop the files into a markdown note to create dummy files, optionally create links to said dummy files in the current note, and optionally store the dummy files in a folder relative to that note without asking, e.g. /Attachments. It would be ideal that the act of creating dummy files is just as streamlined as if the files were stored in the vault. 

In the first gif I imported external links by drag and dropping while holding ctrl. I wish doing the same with PDF++, as illustrated in the second gif, would become as fast as the first. 

![2024-10-18T20_37_05-05_00_TWP-X570-WIN10(Obsidian)](https://github.com/user-attachments/assets/ac7e656d-6934-4b5d-96ac-258561cf717c)

![2024-10-18T20_41_32-05_00_TWP-X570-WIN10](https://github.com/user-attachments/assets/9b8179df-30a4-4672-baef-65034b6f6be1)

On a side note, currently entering a new, non-existing folder path using Create dummy file for external PDF command will place the dummy files in the nearest existing path, instead of creating new directories. Thanks so much for creating this addon and I hope you will have time to consider addressing this issue.

**Comment by RyotaUshio** [comment]
Thanks for the nice suggestion. That would be cool! I'm not sure if I can override Obsidian's default behavior on drag/drop. Will look into that.

> On a side note, currently entering a new, non-existing folder path using Create dummy file for external PDF command will place the dummy files in the nearest existing path, instead of creating new directories.

I can't reproduce this in my environment. Perhaps do you use `\`, instead of `/`, as a path separator? (like `folder\subfolder\file.pdf`)
In Obsidian, `/` is the standard choice so I guess it would work if you use it.
But I will update the path handling logic a bit in the next version so that you can use both.

**Comment by ThinkWithPbody** [comment]
> I can't reproduce this in my environment. Perhaps do you use \, instead of /, as a path separator? (like folder\subfolder\file.pdf)

After testing both \ and / as separators it still wouldn't create the folders needed. I'm on windows 10. But this is a non-issue really, especially if you're already thinking of adding drag and drop to PDF++! 
https://github.com/user-attachments/assets/9b72e90a-c1ab-41e1-a612-abce921e0e92

Currently obsidian, when drag and dropping, does the following:

No modifier keys:
Copy the dropped file to the folder specified under `Options > Files and Links > Default location for new attachments` and insert an internal link to it on the cursor position.

Ctrl held down:
Insert an external link to it on the cursor position.

It would be awesome if you could figure out a way to overwrite this default behaviour, or add new ones based on other modifier keys. I appreciate you looking into improving this experience!

**Comment by RyotaUshio** [comment]
Will be added in the next version ([0.40.12](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.12))!

<img width="762" alt="image" src="https://github.com/user-attachments/assets/aa2ec54f-0e9c-4494-9587-32987e4370ae">

**Comment by ThinkWithPbody** [comment]
I tried the new dummy import today and it works flawlessly. If anything, I found it tedious to manually remove exclamation marks from links but that's consistent with normal obsidian behaviour. Thanks so much for the update!

**Comment by RyotaUshio** [comment]
Yeah, that "!" always annoys me too. I also have seen bunch of people complaining about this on the forum. I considered addressing it in this plugin, but for now it seems to me that it should be an independent plugin because there are also other types of attachments.

**Comment by ThinkWithPbody** [comment]
Hey RyotaUshio, thanks again for adding this feature. I've come again with a minor feature request related to this.

Here in this video, I drag the same file using modifiers, one for external link (Ctrl), one for PDF+ dummy files (Shift)
Notice how the link created by dragging with Ctrl held down only displays the file name and not the whole path
Is it easy to implement that option for the dummy file creation too, so that an | alias is appended to the end?
