### ISSUE TITLE
[FR] Only in the PDF editor area for the box to select the rectangular area highlighting (optional color) picture of the PDF, and does not create a link to the MD function request

### ISSUE THREAD

**Issue by 0xChrisJL** [RyotaUshio/obsidian-pdf-plus#286]
### Describe your request

Hello dear PDF++ author!
Can you add a new box to select a region and highlight the color of the region?
Sometimes it is necessary to highlight some content in the PDF area for eye-catching reminders, PDF is scanned and does not need to be linked to the md document!
thanks

**Comment by RyotaUshio** [comment]
Thanks, I'd suggest using the Pdf Annotator plugin mentioned here in the readme: https://github.com/RyotaUshio/obsidian-pdf-plus?tab=readme-ov-file#note-on-saving-annotations-directly-in-pdf
