### ISSUE TITLE
[FR] Ability to disable continuous scrolling / only show 1 page at a time

### ISSUE THREAD

**Issue by ac8318740** [RyotaUshio/obsidian-pdf-plus#288]
### Describe your request

Adobe pdf reader has the ability to disable scrolling, which then only shows one pdf page at a time. I like this view as it helps me focus in on one page at a time (vs. seeing just the top / bottom of additional pages on top of the one I care about). In screenshot below, "Enable scrolling" is a toggle on/off (from adobe pdf reader).

![image](https://github.com/user-attachments/assets/34290b94-b7d0-4552-8fdf-7ca38c08f3bf)

Wonder if this would be easy to do in PDF++?

BTW, love the plugin so far!

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by RyotaUshio** [comment]
PSA: deleted a potential spam comment. The comment author posted the exact same text in 4 of the issues in this repository at almost the same time, and the text included an unknown link. I also reported the account to GitHub.

**Comment by RyotaUshio** [comment]
Seems like this is an easy addition, so I will add it in the next release!

**Comment by RyotaUshio** [comment]
Maybe additional arrow icons (↓ and ↑) for going to the next/previous page would be necessary in this mode?

**Comment by ac8318740** [comment]
Amazing, thanks RyotaUshio! And on arrow icons - I personally will likely just use pg up / down keyboard buttons, but adobe pdf reader does have those in there (see screenshot), so probably a worthwhile add. 
![image](https://github.com/user-attachments/assets/1f7d1dea-20b0-447d-bf69-fb9c336c943f)

**Comment by RyotaUshio** [comment]
Sorry for being late, I have released [0.40.14](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.14) which includes this change.
For now, we don't have the arrow buttons, but feel free to submit a new FR if you feel the need.

**Comment by ac8318740** [comment]
@RyotaUshio I just tested this out and it seems that pgdown and pgup don't work with this selected. The only way I can navigate pages is by going to "go to page". Is this user error on my part?
