### ISSUE TITLE
[FR] Create note for auto-copy and auto-paste in folder of active pdf file

### ISSUE THREAD

**Issue by JoeKays** [RyotaUshio/obsidian-pdf-plus#291]
### Describe your request

Hi,
would it be possible to introduce an option where the new file for 'Create note for auto-copy and auto-paste' is created in the same folder as the source pdf (aka the active file)?
Thanks!

**Comment by RyotaUshio** [comment]
Thanks, I will close this issue in favor of #249 since this is a special case of that issue.
