### ISSUE TITLE
[FR] Could it be able to move around between pdf++ split and other split in vim mode?

### ISSUE THREAD

**Issue by Lr-2002** [RyotaUshio/obsidian-pdf-plus#293]
### Describe your request

Is there any support to move from pdf ++ to other opened panel ?

**Comment by RyotaUshio** [comment]
Currently, no. What exactl do you want to achieve? Doesn't Tab or Ctrl+Tab suffice?

**Comment by Lr-2002** [comment]
sorry for the late reply 
for example 
![image](https://github.com/user-attachments/assets/610dd746-97d7-4023-8dcf-f24eaf89e857)
I'm using the pdf++ left and the normal edit part right 
how to use keybind to focus on the left or right more fastly?

**Comment by Lr-2002** [comment]
I've tried Ctrl+Tab or Ctrl+Shift+Tab, it doesn't work

**Comment by RyotaUshio** [comment]
Ah got it, so you want to move focus from one side to another, right? Then try Obsidian's built-in commands "Focus on tab group on the left/right".

**Comment by RyotaUshio** [comment]
Other than that, PDF++ provides auto-focus & auto-paste functionality. See the docs for the details.

**Comment by RyotaUshio** [comment]
I'm closing this but let me know if you have further suggestions.
