### ISSUE TITLE
[FR]  Support Custom CSS for PDF Background Color Adjustment

### ISSUE THREAD

**Issue by SR023** [RyotaUshio/obsidian-pdf-plus#296]
### Describe your request

Hi RyotaUshio,

I appreciate all the hard work that has gone into this project; it’s incredibly useful.

I would like to request support for customizing the PDF background color using custom CSS. I often read PDFs for extended periods, and having the ability to change the background color would greatly improve the reading experience by reducing eye strain.

What I’ve Tried: I attempted to change the background color by adding custom CSS, specifically by modifying .pdf-container .pdf-plus-select-box or similar classes. However, these changes did not take effect. I’m wondering if there might be restrictions or overrides that prevent custom background colors from being applied.

Feature Request: Would it be possible to enable support for custom CSS to modify the PDF background color? This would allow users to set a background color that’s easier on the eyes, which is particularly helpful for long reading sessions.

The final result is shown in the figure
![](https://forum-zh.obsidian.md/uploads/default/original/3X/a/0/a0d13df13b918c452616a01afd8ca432bb571011.png)

the img from this link:  https://forum-zh.obsidian.md/t/topic/38211/8

Thank you for considering this request, and for all your efforts on this project!

**Comment by RyotaUshio** [comment]
Thanks!

You can turn the background red (this is just an example) by adding the following CSS snippet and enable the "Adapt to theme" toggle. This will work whether PDF++ is enabled or not.

```css
body {
    --pdf-page-background: red;
}
```

**Comment by SR023** [comment]
but it's not work for me .

<img width="455" alt="image" src="https://github.com/user-attachments/assets/91221abd-bad7-4109-8402-ed83fc55a3e1">
<img width="803" alt="image" src="https://github.com/user-attachments/assets/4601503b-b851-41ab-8d5c-91e4e88068bd">
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/bebe4ca3-b437-4e9d-90b6-59c8177ef624">

**Comment by RyotaUshio** [comment]
Have you enabled "adapt to theme"? What if you relaunch Obsidian?

**Comment by SR023** [comment]
When i enabled "adapt to theme" and relaunch Obsidian,  There's always something that doesn't work.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/7765c66d-8338-46a4-b455-31e9935b58ab">
(<<Test Legends >> It's a test pdf file exported from obsidian. )

**Comment by RyotaUshio** [comment]
What exactly isn't working? As far as I can tell from your image, it seems to be working properly.

**Comment by SR023** [comment]
The problem is the black in the center. it's not red.
