### ISSUE TITLE
copy embed of selection

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#30]
Why is it that when I select `copy embed of selection`, the link after pasting is an embed of the whole PDF?

It should be a bug!
Change the setting to the one shown below and it works fine, before it was `{{link}}`.
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/78469397/087e73a2-fe75-4588-9f86-459842cddd47)

**Comment by RyotaUshio** [comment]
Thanks! Now the `link` template variable contains a subpath such as `#page=1&selection=0,1,2,3&color=red`.
