### ISSUE TITLE
[FR] Assign custom copy formats to single markers

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#31]
Thank you for the great plugin and your great work on it!

In the PDF++ settings a new setting for markers could be introduced: The highlight markers could be bound to specific custom copy formats. For example I have bound the "copy as quote" format to the blue color. Everytime when I switch the markers in the PDF viewer, the custom copy formats switches automatically to the format that is bound to this marker color. Advantage would be here, that you can switch the custom copy format just by changing the markers color in the PDF viewer. For example when the green marker is selected, all my links will have the "bookmark" custom copy format. And if I select the blue color marker, all my links that I assign with that color will have the "Copy as quote" copy format.

**Comment by RyotaUshio** [comment]
Closing this as merged into #33.
