### ISSUE TITLE
Hover sync

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#32]
I don't know why this works when the feature is turned off. Possibly a bug?
![image](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/78469397/f547e62b-227e-4c0e-adeb-1dadacd2d914)

**Comment by RyotaUshio** [comment]
Thanks! You are a great bug finder!

**Comment by math-feng** [comment]
I'm glad to see that you said you solved the problem, but he is still there during my operation, I've upgraded the plugin to the latest version

**Comment by RyotaUshio** [comment]
@math-feng It's working in my environment. Can you try reloading the app?

**Comment by RyotaUshio** [comment]
Sorry I closed it by mistake.

**Comment by math-feng** [comment]
I just tried it again, and Hover sync does work after this feature is turned off.

My operation is: split-screen case, the left is the PDF, the right is the .md file, when I choose to quote the contents of the PDF to the .md file, put the mouse on the link, the left interface can still jump to the PDF is quoted location!

**Comment by math-feng** [comment]
I found in the process of using the embedded content, double-click in the PDF view can not jump to the corresponding content in the .md file, the interface and I described above the same!

**Comment by RyotaUshio** [comment]
From what you described, it sounds like it's not hover sync actually.

"Hover sync (backlinks page → PDF viewer)" means this:

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/81dc1158-74ae-4ef7-8ecc-41132ae577a5

From the plugin settings:

> In the backlinks pane, hover your mouse over an backlink item to highlight the corresponding text or annotation in the PDF viewer.

**Comment by math-feng** [comment]
Hey, I'm experiencing the issue you mentioned in your last sentence. I was wondering if the feature is currently disabled. It would be great if you could help me out with this.

**Comment by RyotaUshio** [comment]
@math-feng Are you referring to this issue?

> I found in the process of using the embedded content, double-click in the PDF view can not jump to the corresponding content in the .md file, the interface and I described above the same!

If so, this is a distinct issue from the original topic of this issue, so please create a new issue. Thanks!
