### ISSUE TITLE
[FR] Embed rectangular region from the PDF as image.

### ISSUE THREAD

**Issue by tu2-atmanand** [RyotaUshio/obsidian-pdf-plus#321]
### Describe your request

Right now the feature, where we can select a region from the PDF and link it to our notes, will only work as long as the PDF is available in the vault folder. When the PDF is moved out of the vault, the following link : 
```md
![[Lorem Ipsum.pdf#page=2&rect=103,433,509,552|Lorem Ipsum, p.2]]
```
will show "could not be found" message.

To solve this issue, and for the users who want to use it this way :  
- A new setting option can be provided for the user to select whether they want the original region linking behavior or embed the region as an image.

- Using the latter option, when the user will select the region from the PDF, and paste it into the note, a new png file will be created in the attachments folder and the link can be used as follows : 
```md
![[Pasted image 20241224164333.png]](Source: [[Lorem Ipsum.pdf#page=2&rect=103,433,509,552|Lorem Ipsum, p.2]])
```

**Comment by RyotaUshio** [comment]
In fact, this is already possible. Right click the rectangle selection button in the toolbar, click "Customize..." and you'll see the option that lets you specify whether rectangle selection should be embedded as an image file.

By the way, my apologies for not replying to your other issues. I'm just being occupied by many other things and have very limited bandwidth.

**Comment by tu2-atmanand** [comment]
> In fact, this is already possible. Right click the rectangle selection button in the toolbar, click "Customize..." and you'll see the option that lets you specify whether rectangle selection should be embedded as an image file.
> 
> Though the format is not exactly as you described, I will add an option for customizing it as it is a heavily requested feature.

Amazing! My bad for not going through the settings before creating this issue. Perhaps, any other user might have missed it, because the amount of features PDF++ provides is astonishing! As I always said, the amount of work which has been put into this plugin is remarkable.

I actually created this issue, after getting an idea from this topic from forum : https://forum.obsidian.md/t/copy-images-from-pdf-reader/93709?u=tu2_atmanand




> By the way, my apologies for not replying to your other issues. I'm just being occupied by many other things and have very limited bandwidth.

Totally understandable! In an open-source environment, it's all dependent on our own availability, anyway. Even I haven't started working on the things I had mentioned in the same issue. It's a long way to go, but surely will be able to implement it soon.
