### ISSUE TITLE
[FR] Increase size of preview pane

### ISSUE THREAD

**Issue by hwangy** [RyotaUshio/obsidian-pdf-plus#325]
### Describe your request

Is it possible to add a setting to increase the size of the preview pane you get when you <cmd>-hover over a link? Or maybe you could drag the corners to change the size?

Thanks!

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a new setting to control the size of the preview pane when hovering over links. This includes adding a slider to adjust the width and height, and modifying the relevant CSS to apply these dimensions.

You can review changes in this commit: https://github.com/mark-addams001881/RyotaUshio-obsidian-pdf-plus-325/commit/85aa778391e6a3a7ab7515ca2eb54ce963da2899.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by RyotaUshio** [comment]
Nice idea.

BTW the AI guys is blocked.

**Comment by hwangy** [comment]
Thanks! Yeah, the AI thing seems crazy...

**Comment by RyotaUshio** [comment]
Released in [0.40.19](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.19)!
If you want to apply more advanced styling, you can target the css class `.pdf-plus-backlink-popover`
