### ISSUE TITLE
Custom right-click context menu gets hidden by Obsidian's builtin menu

### ISSUE THREAD

**Issue by RyotaUshio** [RyotaUshio/obsidian-pdf-plus#34]
> But if I right click there are 2 popups now. The one from obsidian itself with layered on top saying "copy ctrl+c", and your new right context menu. If I right click and press ESC, the obsidian context menu will disappear and now hovering color is working over your new context menu.

_Originally posted by @N3C2L in https://github.com/RyotaUshio/obsidian-pdf-plus/issues/28#issuecomment-1925290400_

**Comment by RyotaUshio** [comment]
@N3C2L

Hmm... that's strange, and in my environment, it's working just fine...

- Can you try reloading the app after updating PDF+, and reopening the PDFs?
- If it doesn't help, can you show me a screen recording of where this bug is happening, and also show me the result of the command "Show debug info"?

**Comment by N3C2L** [comment]
I haven't use a screen recording software recently, any recommendations?
I am on Windows (not a developer), just a random user, no Linux or MacOS.
I have reloaded the app and restarted Obsidian, no difference.
It looks like a context menu of the windows OS itself, not a context menu of Obsidian.

**Comment by RyotaUshio** [comment]
Thanks!

> I haven't use a screen recording software recently, any recommendations?

It's fine as long as I can understand what it looks like. Even taking a picture with your smartphone will be okay if it's clear enough.

> It looks like a context menu of the Windows OS itself, not a context menu of Obsidian.

I see. I don't have a Windows machine so this issue might take some time until it gets resolved.
I appreciate your cooperation!

**Comment by RyotaUshio** [comment]
Just released 0.27.12, which contains a potential fix for this.

**Comment by N3C2L** [comment]
Thanks a lot!
It's working good now on my OS.
Only your good context menu appears now.

**Comment by RyotaUshio** [comment]
I'm glad it finally worked. Thank you for your contribution!
