### ISSUE TITLE
[BUG] Cannot use display text format

### ISSUE THREAD

**Issue by zuluwi** [RyotaUshio/obsidian-pdf-plus#4]
When I use `{{file.basename}}, {{page}}/{{pageCount}}, "{{selection}}"` or `{{file.basename}}` as **Display text format**, I get the following errors

![resim](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/111116092/4912186b-ae27-457a-83ab-c293f162658f)

![resim](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/111116092/bbb526c0-39d3-4750-bd52-15f6333bb5be)

**Comment by RyotaUshio** [comment]
Thanks again! I've made a silly mistake and it didn't work when there was no tab linked to the PDF tab.

Now it's fixed and has been released as [0.12.1](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.12.1).
