### ISSUE TITLE
[Disscussion] better context view in backlink panel?

### ISSUE THREAD

**Issue by SSmJaE** [RyotaUshio/obsidian-pdf-plus#40]
When we make an annotation in Zotero's PDF viewer, we can comment on that annotation directly in the comment card (the comment in the left panel, not the entry comment in the right panel).

By using this plugin, we could distribute the annotation throughout the vault, and we might also take some comments around that annotation.

since this plugin could display the backlink for a specific pdf page, is it possible to display more context when triggering the context button in the backlink panel (for now this button doesn't affect anything), like the behaviour in the markdown file?

Currently I use three monitors, there is no such requirement for this feature actually, I could just display multiple windows at the same time, one for pdf, one for markdown.
It is also a quality of life improvement, I just wonder if there is a way to make the backlink view better, more like zotero or zotlit's annotation view.

**Comment by RyotaUshio** [comment]
The backlink view is, in fact, a very sophisticated mechanism. Naively iterating over the link caches and reading the file contents will cause a noticeable time lag and possibly UI blocking.
The Obsidian team really did a tremendous job implementing the native backlink pane in such an efficient way.
So I'm afraid it's unlikely to be feasible to create our own view.

However, you can improve the backlink pane by combining the [Better Search Views](https://github.com/ivan-lednev/better-search-views) (which renders markdown in the backlink pane) plugin and the custom callout feature that PDF++ 0.29.2 has introduced.

1. Select a range of text that you want to add a comment.
  <img width="1552" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/f203589a-8792-4ff3-a6a8-d1965af500cc">

2. Copy a link to the selection with following copy template (this is included as one of the default templates in the latest version, but the users from the older versions will have to manually add it):
   ```
   > [!{{calloutType}}|{{colorName}}] {{linkWithDisplay}}
   > > {{text}}
   > 
   > 
   ```

3. Now, paste it to a markdown file, and add your own comment in the callout, like so
   <img width="785" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/aa8f5780-b976-41f7-8763-c4b31e9a2192">

4. Then, the backlink pane will look like this:
   <img width="1552" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/35d47e17-7f61-440a-8f8d-556f8bc28676">

**Comment by SSmJaE** [comment]
this approach is good enough 👍
