### ISSUE TITLE
[FR] Changing page layout in embed

### ISSUE THREAD

**Issue by zuluwi** [RyotaUshio/obsidian-pdf-plus#5]
If the page layout is set to double page in the pdf viewer, it also shows double page in the embed, which makes it very difficult to read. Is it possible to set a page layout in the embed that is independent of the main pdf viewer?

![resim](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/111116092/c58f23be-3223-4b3d-96a1-992db2bbe030)

**Comment by RyotaUshio** [comment]
This is an awesome idea! I somehow managed to find a way to do this, and it's now released as [0.15.0](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.15.0).
