### ISSUE TITLE
Allow us bi directional linking [FR] 

### ISSUE THREAD

**Issue by KuecukMimarBey** [RyotaUshio/obsidian-pdf-plus#57]
First of all thank you for this great plug in

It would be great if we could insert links into the pdf

- Inserting links freely into the pdf page ( for linking files to e.g images & graphs )
- Inserting links directly into any word/text pharagraph in the pdf page

It would be so much simplier if we could handle any pdf like an normal file, why ? 
so we can bi-directional linking ...

Is this possible ?

**Comment by RyotaUshio** [comment]
Can you explain your request more clearly? For example, links from what to what?

**Comment by KuecukMimarBey** [comment]
Creating links inside our pdfs to our md - files

Could you tell me which part you didnt get ?

**Comment by RyotaUshio** [comment]
I see. What I didn't get was

> for linking files to e.g images & graphs

but now it's clear.

The current status of this plugin is:

1. Markdown to PDF: possible with Obsidian's built-in features.
2. A PDF to the same PDF: already possible with PDF++.
3. A PDF to a different PDF: not implemented yet, but possible.
4. PDF to markdown: not implemented yet, but possible.

For 2, all the links you copy within a PDF can be "pasted" into any text selection in the same PDF file if you enable PDF file editing.

3 & 4 are technically possible, but probably I will not add them to PDF++ in the short term. This is because it is hard to auto-update links inside PDFs when the target file is renamed, unlike in the case of markdown files.
I don't want to have a lot of links in my PDFs that will not work once I rename the target files.

However, you can achieve something like bi-directional linking without these kinds of concerns with the existing features of PDF++.
- You can double-click a text highlight or annotation to open the backlink (i.e. the markdown file that links to the highlight)
- or you can hover+ctrl over a highlight or annotation to show a popover preview of the backlink

Demo videos can be found here: https://ryotaushio.github.io/obsidian-pdf-plus/backlink-highlighting-basics.html

**Comment by RyotaUshio** [comment]
So if you want to jump from a text in the PDF to a markdown file, just copy a link to the text selection in the PDF viewer
and paste it into the markdown file.

Then, you will be able to go to the markdown file by double-clicking on the text highlight in the PDF.

**Comment by KuecukMimarBey** [comment]
"However, you can achieve something like bi-directional linking without these kinds of concerns with the existing features of PDF++.

You can double-click a text highlight or annotation to open the backlink (i.e. the markdown file that links to the highlight)"


Thank you i just tested it and it works

it is with some friction, so i was thinking ... 
Is it possible to add the automatic window which apears when we use the bracklets [[ ]] to insert the right - obsidian file link ? 

right know it would be more than enough if the above feature would be possible
my conserns about the automatic updating of links when i rename them are quite less and i can see myself to do it manuelly

**Comment by RyotaUshio** [comment]
> Is it possible to add the automatic window which apears when we use the bracklets [[ ]] to insert the right - obsidian file link ?

Where and when do you want the popup to show up?

> my conserns about the automatic updating of links when i rename them are quite less and i can see myself to do it manually

I'm still very concerned so it's unlikely to happen in the near future, but if you could do pull requests I will happily review them.

**Comment by KuecukMimarBey** [comment]
Thank you 

Where and when do you want the popup to show up? And what do you expect to happen after you select one of the suggestions? (Please describe you idea clearly

1. When I use the tool "Write highlight to pdf & copy link with format XXXX"
2. It creates me a highlight with - the authors name - date and time - copy link button / edit button / delet button
3. There I want to edit the highlight | edit means, inserting the obsidian file link into the contents text box
4. Exactly there i want the popup show up when i tipe the bracklets [[...]] 

Right know i do it exactly like that, i like the workflow, but it is manuelly, so it creates friction when i want to enter a flowstate of productivity & learning

**Comment by RyotaUshio** [comment]
Thanks now it's clear

It is not impossible but will definitely require a lot of work. Probably I will have to re-implement the whole logic of Obsidian's link suggested all by myself.

I DO agree that will be a nice feature to have. But it's not what I can add in the short term.

**Comment by KuecukMimarBey** [comment]
Take your time, it will be better if you do it properly 

I can imagine that it would benefit a lot of obsidan users which struggle with the current restricted pdf interface of obsidian

i cant code, i would have loved to help :/

**Comment by RyotaUshio** [comment]
Plus, I wouldn't suggest writing your notes inside the contents box in the first place. That's the conventional way of PDF annotation and is not the main purpose of this plugin.

To make the best of Obsidian's power, I recommend writing down your thoughts in normal markdown files. Then you can connect the md to any pdfs or any other markdown notes.

**Comment by KuecukMimarBey** [comment]
No, i agree with you. 

The context box whole purpose for me was to link to any other md - file in obsidian 

in this files
- i could have created ideas only by reading the pdfs 
- or Ideas i already had and see fit to link them to the pdf 

i get that handling the linking system of md files and implementing it to pdf files in obsidian is hard, but i can imagine that the learning, productivity in obsidan gets a strong boost ⚡ by getting this done

**Comment by RyotaUshio** [comment]
> The context box whole purpose for me was to link to any other md - file in obsidian

Then, I would suggest just using PDF++'s existing features.
Your original request was bi-directional linking, and it can be achieved by the existing features but not by putting wikilink inside the content box.

Implementing link suggestions in the content box is not impossible but so far from the main line of this plugin's principle that it can degrade the maintainability of the project. Therefore I'm afraid it is unlikely to happen unless someone sends me a pull request.
