### ISSUE TITLE
[FR] Rectangular area boundaries are colored

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#58]
Can you use a rectangular box to select the PDF, the boundaries of the boxed area can also be marked with color and there is a link in the region, click it can jump to the corresponding position.

**Comment by RyotaUshio** [comment]
<img width="1552" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/ebe65e74-d6a3-4b59-8e2e-ec4aeca9d704">

Work in progress!

**Comment by RyotaUshio** [comment]
Released as [0.37.0-beta](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.0-beta).
