### ISSUE TITLE
Indicator that a native PDF highlight has a backlink.

### ISSUE THREAD

**Issue by tptran96** [RyotaUshio/obsidian-pdf-plus#61]
### Describe your request

Would it possible to add an icon or underline a native PDF highlights that has a backlink attatched to it just to distinguish it from other highlights?

**Comment by RyotaUshio** [comment]
Work in progress!

<img width="292" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/3091a585-5d01-47a5-938a-b967b456835d">

<img width="318" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/a56fc239-767c-4194-95d0-b193de6de6d3">

**Comment by RyotaUshio** [comment]
Released as [0.37.0-beta](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.0-beta).
