### ISSUE TITLE
Ability to change pdf highlights color from the right-click menu.

### ISSUE THREAD

**Issue by tptran96** [RyotaUshio/obsidian-pdf-plus#62]
### Describe your request

Is it possible to change the highlight color from the right-click menu?

**Comment by RyotaUshio** [comment]
Will be available in the next release.

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/4d9e90f0-3877-49d5-b80e-ee41911028fb

**Comment by RyotaUshio** [comment]
Released as [0.37.0-beta](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.0-beta).

**Comment by tptran96** [comment]
Thank you soo much for this. Would it be possible to do the same for highlights written natively in a pdf editor?

**Comment by RyotaUshio** [comment]
That's also possible. I will add it in a future release!

**Comment by RyotaUshio** [comment]
For performance reasons, showing context menu items for changing highlight colors is a bit difficult. So I added a dropdown menu in the annotation editing modal instead. It's now available as [0.37.0-beta8](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.0-beta8).

**Comment by RyotaUshio** [comment]
https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/f259dd31-d567-489a-a60a-0e8fc19ad3a9
