### ISSUE TITLE
[FR] Added settings for customizing the color of the rectangular selection area

### ISSUE THREAD

**Issue by PennHui666** [RyotaUshio/obsidian-pdf-plus#70]
## Describe the issue
My obsidian theme is Minimal-Light mode-Sky. In this theme mode, the color of the rectangular selection area is gray and opaque, and the content in the selection area cannot be seen. So I tried switching to several different themes and found that the color of the rectangular selection area would change under different themes, which was roughly the same as the background color of the theme.

## Screenshot of problem
![Snipaste_2024-03-02_17-05-14](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72249772/d6f6b3ac-433c-40b0-9966-d09c048ea6ef)

## Suggestions for Improvement
Allows customizing the background color and opacity of the rectangular area through `style settings`, or adding this option to the settings of pdf++.

**Comment by RyotaUshio** [comment]
Thanks!
It's fixed in [0.37.2](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.2).

**Comment by PennHui666** [comment]
Awesome, your fix was so quick!
