### ISSUE TITLE
[FR] Automatically close the sidebar

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#72]
### Describe your request

When we finish viewing the PDF's table of contents, click on the PDF's content to automatically close the sidebar.

the function is similarly with the plugin:https://github.com/skelato1/obsidian-auto-hide

**Comment by RyotaUshio** [comment]
Implemented! 
https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.4

**Comment by RyotaUshio** [comment]
FYI, PDF++ had had commands to open & close the sidebar
