### ISSUE TITLE
[FR] Annotation on the rectangular area

### ISSUE THREAD

**Issue by roosteer** [RyotaUshio/obsidian-pdf-plus#75]
### Describe your request

As with zotero and other apps, the ability to annotate and display a rectangular area from the editor

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/48920108/9912459c-045e-4c63-aff4-55913f8d6d88

**Comment by RyotaUshio** [comment]
I recommend you to use Hover Editor:


https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/c638032e-8795-4c72-afec-b03cca4873ed

**Comment by RyotaUshio** [comment]
This method works for text selections and annotations as well.

**Comment by roosteer** [comment]
Thank you!
