### ISSUE TITLE
[FR] For the rectangular selection add to the context menu the possibility to copy the highlighted area as an image

### ISSUE THREAD

**Issue by roosteer** [RyotaUshio/obsidian-pdf-plus#76]
### Describe your request

For the rectangular selection add to the context menu the possibility to copy the highlighted area as an image

**Comment by RyotaUshio** [comment]
Just to confirm, are you aware of the "Paste as Image" option?

<img width="770" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/7ae48ba7-d406-4263-aee1-00db6eb2d42c">

**Comment by RyotaUshio** [comment]
Released in https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.37.8
