### ISSUE TITLE
[FR] Improvement of operating logic

### ISSUE THREAD

**Issue by math-feng** [RyotaUshio/obsidian-pdf-plus#91]
### Describe your request

In the process of using it, I can feel that every time the mouse wheel scrolls on the PDF, the plug-in starts working, thus causing the effect of slow page loading, but sometimes we just browse the content of the PDF, not to mark anything.

So I suggest to start working only when we mouse click on the color palette or rectangle area, and also only work on the current page, I don't know if it can be realized.

**Comment by RyotaUshio** [comment]
Hm, I haven't experienced a noticeable slowdown myself. Do you have obvious differences in the loading time between when PDF++ is enabled and when it's not?

**Comment by math-feng** [comment]
It's really not caused by the plugin, after I turn off the plugin, scrolling the PDF is also only a few pages nearby is smoother, and the ones behind it go blank, requiring me to wait for about three seconds before the screen is displayed. May I ask if yours is like this.

**Comment by RyotaUshio** [comment]
> It's really not caused by the plugin

Then there is little hope the lag is reduced by any effort made by this plugin, unfortunately.

> requiring me to wait for about three seconds before the screen is displayed

Three sec is quite a long time. PDF page loading is "lazy" by nature, meaning each page is loaded when it becomes necessary so there can be some lag, but it should not take that long. I haven't experienced that long loading time.

If I remember correctly, you are on Windows 10, right? It's been about three years since Windows 11 came out, so I guess your machine is not very new. So it might be your computer that is to be blamed.

**Comment by math-feng** [comment]
My system is win11.  The three seconds is a manual estimate on my part, the actual value was not measured. Probably because I have too many plugins installed.May I ask how you manage plugins.

**Comment by RyotaUshio** [comment]
> My system is win11.

Oh my bad.

> Probably because I have too many plugins installed.May I ask how you manage plugins.

Yeah 50+ plugins is quite a lot, so you might need to turn off some of them when you don't really need them.
But in my experience, turning off all the CSS snippets can sometimes bring much more improvement to the performance.

**Comment by math-feng** [comment]
I've used many of your plugins and you've done a great job with all of them, thank you very much.

Back to the issue of PDF browsing speed, after I turned off the plug-in LaTeX-like Theorem & Equation Referencer for Obsidian speed greatly improved.

**Comment by RyotaUshio** [comment]
> after I turned off the plug-in LaTeX-like Theorem & Equation Referencer for Obsidian speed greatly improved.

It's my first plugin and also is very complicated so I'm not surprised it's causing some performance degradation. I will look into it!

**Comment by math-feng** [comment]
Thank you very much!

**Comment by RyotaUshio** [comment]
Yeah I'm aware of the problem, but thanks anyways!
